name: 'PR description checker'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
    - name: Print Body of PR
      run: echo The Body of the PR is ${{ github.event.pull_request.body }}
