name: 'PR description checker'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR description
      run: if echo ${{ ! github.event.pull_request.body }}
        echo "Please provide a description to your PR."
        exit 1
