name: 'PR description checker'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR description
      run: |
        if ${{ ! github.event.pull_request.body }}; then
          echo "Please provide a description to your PR."
          exit 1
        else
          echo "Thank you for providing a description!"
          exit 0
        fi
